# Generated by Django 5.1.1 on 2024-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('about_machine', models.TextField(default='')),
                ('image_1', models.FileField(null=True, upload_to='media')),
                ('tarahi_zaheri', models.TextField(default='')),
                ('image_2', models.FileField(null=True, upload_to='media')),
                ('moshakhasat_fanni', models.TextField(default='')),
                ('image_3', models.FileField(null=True, upload_to='media')),
                ('tarahi_dakheli', models.TextField(default='')),
                ('image_4', models.FileField(null=True, upload_to='media')),
                ('mazaya', models.TextField(default='')),
                ('image_5', models.FileField(null=True, upload_to='media')),
                ('images', models.FileField(null=True, upload_to='media')),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(default='', null=True, unique=True)),
            ],
        ),
    ]
