# Generated by Django 5.1.1 on 2024-10-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_alter_review_image_1_alter_review_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='embed_code',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
