# Generated by Django 5.1.1 on 2024-11-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_review_titr'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sub_titr',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
