# Generated by Django 5.1.1 on 2024-11-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_review_sub_titr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='titr',
            field=models.TextField(default='', max_length=100),
        ),
    ]
