# Generated by Django 5.1.1 on 2024-11-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_alter_review_titr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='images',
        ),
    ]
