# Generated by Django 5.1.1 on 2024-11-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_remove_review_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hashtag1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='hashtag2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
