# Generated by Django 5.1.1 on 2024-11-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_review_hashtag1_review_hashtag2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('titr', models.TextField(default='', max_length=100)),
                ('sub_titr', models.CharField(blank=True, max_length=150)),
                ('mozo1', models.TextField(default='', max_length=100)),
                ('sub_mozo1', models.TextField(default='', max_length=100)),
                ('image_1', models.FileField(blank=True, null=True, upload_to='media')),
                ('mozo2', models.TextField(default='', max_length=100)),
                ('sub_mozo2', models.TextField(default='', max_length=100)),
                ('image_2', models.FileField(blank=True, null=True, upload_to='media')),
                ('mozo3', models.TextField(default='', max_length=100)),
                ('sub_mozo3', models.TextField(default='', max_length=100)),
                ('image_3', models.FileField(blank=True, null=True, upload_to='media')),
                ('mozo4', models.TextField(default='', max_length=100)),
                ('sub_mozo4', models.TextField(default='', max_length=100)),
                ('image_4', models.FileField(blank=True, null=True, upload_to='media')),
                ('image_5', models.FileField(blank=True, null=True, upload_to='media')),
                ('image_6', models.FileField(blank=True, null=True, upload_to='media')),
                ('date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='', null=True, unique=True)),
                ('hashtag1', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('hashtag2', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
