# Generated by Django 5.1.1 on 2024-11-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_khabar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khabar',
            name='sub_mozo1',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='khabar',
            name='sub_mozo2',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='khabar',
            name='sub_mozo3',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='khabar',
            name='sub_mozo4',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='khabar',
            name='sub_titr',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
