# Generated by Django 5.1.1 on 2024-11-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0010_alter_khabar_sub_mozo1_alter_khabar_sub_mozo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khabar',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
