# Generated by Django 5.1.1 on 2024-12-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0011_khabar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='mazaya',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='moshakhasat_fanni',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='tarahi_dakheli',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='tarahi_zaheri',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
