# Generated by Django 5.1.1 on 2024-12-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0012_alter_review_mazaya_alter_review_moshakhasat_fanni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khabar',
            name='mozo1',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='khabar',
            name='mozo2',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='khabar',
            name='mozo3',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='khabar',
            name='mozo4',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='khabar',
            name='sub_mozo1',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='khabar',
            name='sub_mozo2',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='khabar',
            name='sub_mozo3',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='khabar',
            name='sub_mozo4',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
