# Generated by Django 5.1.4 on 2025-01-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0013_alter_khabar_mozo1_alter_khabar_mozo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khabar',
            name='hashtag2',
        ),
    ]
