# Generated by Django 5.1.4 on 2025-01-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0014_remove_khabar_hashtag2'),
    ]

    operations = [
        migrations.AddField(
            model_name='khabar',
            name='hashtag2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
