# Generated by Django 5.1.4 on 2025-01-18 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0017_alter_dailypageview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypageview',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 18, 14, 58, 14, 480532, tzinfo=datetime.timezone.utc)),
        ),
    ]
