# Generated by Django 5.1.4 on 2025-01-21 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0019_alter_dailypageview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypageview',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 21, 20, 13, 33, 278464, tzinfo=datetime.timezone.utc)),
        ),
    ]
