# Generated by Django 5.1.4 on 2025-01-21 20:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0020_alter_dailypageview_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='dailypageview',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 21, 20, 21, 30, 67653, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='CarSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('production_year', models.PositiveIntegerField(blank='True', null='True')),
                ('engine_capacity', models.PositiveIntegerField(blank='True', null='True')),
                ('cylinders', models.PositiveIntegerField(blank='True', null='True')),
                ('valve', models.PositiveIntegerField(blank='True', null='True')),
                ('tanafos', models.PositiveIntegerField(blank='True', null='True')),
                ('torque', models.PositiveIntegerField(blank='True', null='True')),
                ('hp', models.PositiveIntegerField(blank='True', null='True')),
                ('max_speed', models.PositiveIntegerField(blank='True', null='True')),
                ('sefr_sad', models.DecimalField(blank='True', decimal_places=3, max_digits=3, null='True')),
                ('gearbox', models.CharField(max_length=50)),
                ('differential', models.CharField(max_length=50)),
                ('talig_jolo', models.CharField(max_length=50)),
                ('talig_agab', models.CharField(max_length=50)),
                ('weight', models.PositiveBigIntegerField(blank='True', null='True')),
                ('fuel_tank', models.PositiveIntegerField(blank='True', null='True')),
                ('masraf_sokht', models.DecimalField(blank='True', decimal_places=3, max_digits=3, null='True')),
                ('ring', models.CharField(max_length=50)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='auto.review')),
                ('parent_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='auto.parentmodel')),
            ],
        ),
    ]
