# Generated by Django 5.1.4 on 2025-01-22 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0021_parentmodel_alter_dailypageview_date_carspecs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspecs',
            name='parent_brand',
        ),
        migrations.AddField(
            model_name='carspecs',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carspecs',
            name='mother_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='cylinders',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='differential',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='engine_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='fuel_tank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='gearbox',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='hp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='masraf_sokht',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='max_speed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='production_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='ring',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='sefr_sad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='talig_agab',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='talig_jolo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='tanafos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='torque',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='valve',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailypageview',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 22, 10, 51, 6, 492530, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='ParentModel',
        ),
    ]
