# Generated by Django 5.1.4 on 2025-01-22 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0022_remove_carspecs_parent_brand_carspecs_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecs',
            name='masraf_sokht',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='sefr_sad',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='dailypageview',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 22, 17, 23, 28, 351519, tzinfo=datetime.timezone.utc)),
        ),
    ]
